# Generated by Django 5.1.7 on 2025-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizTemplateApp', '0003_quiz_category_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
