# Generated by Django 5.0.2 on 2025-04-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizTemplateApp', '0006_add_ss_quiz_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssquizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssquizattempt',
            name='quiz_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ssquizattempt',
            name='quiz_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ssquizattempt',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ssquizattempt',
            name='user_answers',
            field=models.JSONField(default=dict),
        ),
    ]
