# Generated by Django 5.0.2 on 2025-04-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizTemplateApp', '0008_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='QuizTemplateApp.challenge'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
